name: Generate Snake Game from GitHub Contribution Grid
on:
  schedule:
    - cron: "54 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Generate Snake Game
        uses: Platane/snk@v2.2.1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
